language: python
python:
- 3.4
- 3.5
- 3.6
- 3.7
- 3.8
install:
- pip install numpy
notifications:
  slack:
    secure: ZZUAtZCV8uziea+nDAVEk0YiLgCaSBXJ2Irms1SiXE8CHqYSqF731FliQYrXcSfzdkenjLWkyquY34GlqQLqyIAzYBgbvrAWg7vJP7Bsl1Hh6JOrKqTo2ciRN5Pa0fSLVx8TxDe2DAOVG0WSOa3AYY9k38ds6ynu6ze55edVBSq20zMEfgLfhU74muqjsUjLlwGVprnl1UHkxArZT7/veeYc/rFjWS23ccd3aoCIhAuxZ4w3XCeORJFLpiKiZCqGxu9zqWYjvIe485SMTJy5WuJWSVig5iQVyBlVi5J0HsmOr8UvGFwNCEjIlLHhYkevKQAcWH2mYY7F8c0hOwiE3Vg7HGxpxD8hTdFzgaV/eWs9LtW48ZC7VeZbKa6aCRtAe/24XAPbkzaQyk1rsePjEp/9FbsOu9pQHlFQp55m1iiuE5+CR6MZc1MyWhkt2ORipjA2gKHw/lBtrMnUa5oxyKoO2NsGAJQ5XQnmbtvfxo/PvmV4P2DG9stb0UQ1kDOhXPb5raGKwdiESBiuWHsNV31sT6xcBIjJuOkpWOGcIxtsQcdZPgRLEz1BSJzn2g8a87ByTFLZMBdkhov9NAby/4ZqZcm1kGl9Lz6/2P5bQCKsMoxL75QzNlyv59c1+ohAbByl+tEct85TjYew+EYifdyBmfkENt43Tt5onGz58zA=
script: python -m unittest discover
